name: Generate IPs

on:
  schedule:
    # 东八区每天凌晨 00:00 运行，每72小时一次
    # UTC = CST - 8小时，00:00 CST = 16:00 前一天 UTC
    # 使用 cron 每3天运行
    - cron: '0 16 */3 * *'
  workflow_dispatch: # 支持手动触发
  push:
    branches:
      - main
    paths:
      # 仅当特定文件变更时触发，排除脚本和工作流
      - 'ip.txt'
      - 'ips.txt'
      - 'ip.csv'

jobs:
  generate-ips:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以支持 git 操作

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 使用较新版本

      # 安装系统依赖
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmaxminddb-dev

      # 运行脚本，禁用内部推送
      - name: Run ip-filter-speedtest-api.py
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          python ip-filter-speedtest-api.py --url=https://bihai.cf/CFIP/CUCC/standard.csv,https://bihai.cf/CFIP/CMCC/standard.csv
        continue-on-error: false

      # 检查生成的文件
      - name: Check generated files
        run: |
          ls -l ip.txt ips.txt ip.csv || echo "部分文件可能未生成"

      # 配置 Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 提交更改
      - name: Commit changes
        run: |
          git add ip.txt ips.txt ip.csv
          if git diff --staged --quiet; then
            echo "没有更改需要提交"
            exit 0
          fi
          git commit -m "Update IP lists and test results [ci skip]"
        continue-on-error: true # 允许无更改时继续

      # 推送更改
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
        continue-on-error: false

      # 上传 artifacts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ip-files
          path: |
            ip.txt
            ips.txt
            ip.csv
            speedtest.log
          if-no-files-found: warn
