name: Generate IPs Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ips.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行，相当于 KST 09:00

permissions:
  contents: write

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Make iptest.sh and iptest executable
        run: |
          chmod +x iptest.sh
          chmod +x iptest

      - name: Verify files
        run: ls -l

      - name: Run collect_ips.py
        run: python collect_ips.py

      - name: Commit and push ips.txt
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ips.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ips.txt with latest IPs"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ips.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ips-txt
          path: ips.txt
