name: Generate IPs Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # 授予写入权限以推送文件

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Make iptest.sh and iptest executable
        run: |
          chmod +x iptest.sh
          chmod +x iptest

      - name: Run generate_ips.py
        env:
          SPEED_TEST_API_KEY: ${{ secrets.SPEED_TEST_API_KEY }}
        run: python generate_ips.py

      - name: Commit and push ips.txt
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ips.txt
          git commit -m "Update ips.txt with latest generated IPs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ips.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ips-txt
          path: ips.txt
