name: Generate IPs Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ips.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 16 */3 * *'

permissions:
  contents: write

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 charset-normalizer

      - name: Make iptest.sh and iptest executable
        run: |
          chmod +x iptest.sh || echo "iptest.sh not found, continuing"
          chmod +x iptest || echo "iptest not found, continuing"

      - name: Verify files
        run: ls -l

      - name: Run collect_ips.py
        run: python collect_ips.py

      - name: Commit and push ips.txt
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ -f ips.txt ]; then
            git add ips.txt
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update ips.txt file"
              git push
            fi
          else
            echo "ips.txt not found, skipping commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: always() # 即使失败也上传
        uses: actions/upload-artifact@v4
        with:
          name: workflow-artifacts
          path: |
            ips.txt
            ip.csv
            speedtest.log
          if-no-files-found: warn # 如果文件缺失，仅警告
